FROM python:3.12-bullseye

WORKDIR /app

RUN --mount=type=bind,source=requirements.txt,target=/tmp/requirements.txt \
    --mount=type=cache,target=/root/.cache/pip \
    pip install -r /tmp/requirements.txt

COPY config /app/config
COPY tts_api /app/tts_api

CMD [ \
    "gunicorn", \
    "--config", "config/gunicorn.conf.py", \
    "--worker-tmp-dir", "/dev/shm", \
    "--log-config", "config/logging.ini", \
    "tts_api.fastapi_app:app" \
]
