services:

  n8n:
    image: n8nio/n8n
    container_name: n8n_master
    depends_on:
      - db_postgres
      - processing_api
    ports:
      - "5678:5678"
      - "5679:5679"
    volumes:
      - ~/.local/n8n/n8n_service:/home/node/.n8n
    env_file:
      - .env
    environment:
      - N8N_RUNNERS_ENABLED=true

  db_postgres:
    image: postgres:17.5
    container_name: n8n_db
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - ~/.local/n8n/db_postgres:/var/lib/postgresql/data

  processing_api:
    build:
      context: processings_api
      dockerfile: Dockerfile
    container_name: processing_api
    restart: always
    ports:
      - "5010:5000"
    expose:
      - 5000
    volumes:
      - $PWD/cache_articles:/data/cache_articles

  tts_api:
    build:
      context: tts_api
      dockerfile: Dockerfile_tts_api
    container_name: tts_api
    environment:
      - HF_HOME=/model
      - SUNO_USE_SMALL_MODELS="1"
    ports:
      - 5011:5000
    expose:
      - 5000
    volumes:
      - $HOME/.cache/huggingface/models:/model
      - $HOME/.cache/suno:/root/.cache/suno
